name: Test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: check
        run: go version
      - name: check GOPATH
        run: echo $GOPATH
      - name: install wire
        run: go get -u github.com/google/wire/cmd/wire
      - name: run wire
        run: go generate ./...
        working-directory: ./golang
        #run: $(go env GOPATH)/bin/wire
        #working-directory: ./golang
      - name: check files
        run: ls -la
        working-directory: ./golang
      - name: install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
      - name: Run lint
        run: >-
          golangci-lint run
          --disable-all
          --enable=gofmt
          --enable=vet
          --enable=gocyclo
          --enable=golint
          --enable=errcheck
          --enable=misspell
          --enable=wsl
          --enable=lll
          --enable=goimports
  test:
    runs-on: ubuntu-latest
    strategy:
      # To run test for multiple version of Golang
      matrix:
        go: [ '1.15' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: install wire
        run: go get -u github.com/google/wire/cmd/wire
      - name: run wire
        run: $(go env GOPATH)/bin/wire
        working-directory: ./golang
      - name: Run test
        run: go test -v ./
        working-directory: ./golang
